### ISSUE TITLE
执行 python3 mamge.py 报错

### ISSUE THREAD

**Issue by arch3rPro** [phantom0301/VulCloud#1]
报错信息如下：
···
root@ubuntu:/opt/VulCloud# python3 manage.py
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    app = create_app(os.getenv('FLASK_CONFIG') or 'default')
  File "/opt/VulCloud/app/__init__.py", line 44, in create_app
    from .main import main as main_blueprint
  File "/opt/VulCloud/app/main/__init__.py", line 5, in <module>
    from . import views, forms, errors
  File "/opt/VulCloud/app/main/views.py", line 23, in <module>
    executor = ThreadPoolExecutor(cfg.DOCKER_BUILDER_MAX_NUM)
AttributeError: type object 'DevelopmentConfig' has no attribute 'DOCKER_BUILDER_MAX_NUM'
···

**Comment by phantom0301** [comment]
更新项目代码后没有同步更新 conf 配置文件，在 conf/config.py 文件的 Config 类增加 配置项  DOCKER_BUILDER_MAX_NUM = 1即可

**Comment by phantom0301** [comment]
最新的项目已添加该选项

**Comment by phantom0301** [comment]
更新中发现部分静态资源也没有同步更新到github， 已修复，请更新一下项目
